### ISSUE TITLE
Git Blame: Line blame is not aligned properly

### ISSUE THREAD

**Issue by mingyc** [solomonkinard/public#12] opened 2024-02-22 08:05 UTC
See an example of [the file](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/client_hints/client_hints_factory.cc;l=9)

![Screenshot 2024-02-22 at 5 01 49 PM](https://github.com/solomonkinard/public/assets/504463/94c347d1-a46d-46f7-90d4-2ce43d3f9c0d)

## Environment
The editor ruler is set at the 80th column, and the editor font I am using is Fira Code, which is a monospace font.

## Expected Behavior
The line blames by Git Blame extension should render all blames after the ruler.

## Actual Behavior
They are not aligned at all.

**Comment by tobiaskraus** [comment] 2024-05-02 11:28
I have the same issue in all my files:
![image](https://github.com/solomonkinard/public/assets/49694150/b1b9612e-d53b-4dd8-9378-999be4cb599b)

.prettierrc.js extends from another prettier-config in my node_modules (with require). In there is defined:
 `printWidth: 120`. Maybe it has sth. to do with it.

**Comment by solomonkinard** [comment] 2024-07-21 08:48
@tobiaskraus, Your problem might be fixed in [0.2.38](https://marketplace.visualstudio.com/items/solomonkinard.git-blame/changelog), but neither of these issues have been reproduced exactly so far?

@mingyc, Your description may be a different problem with Git Blame, and it's unclear if the bug that you described is fixed in 0.2.38?

**Comment by solomonkinard** [comment] 2024-08-11 07:24
It's been a few weeks and without hearing back. Closing this bug due to inability to reproduce without feedback. Thanks.

**Closed by solomonkinard** 2024-08-11 07:24 UTC

**Comment by Liushitong** [comment] 2025-02-06 02:10
This issue might be related to `editor.fontFamily`. I also used `Fira Code` in my settings and encountered a similar problem. When I commented out my `editor.fontFamily` setting and used the default, `git-blame.config.inlineBlameStartColumn` worked fine.

**Comment by solomonkinard** [comment] 2025-02-07 11:12
[Fira Code](https://github.com/tonsky/FiraCode/wiki/VS-Code-Instructions) calls for `"editor.fontLigatures": true`, which combines pairs of individual characters into one (e.g. fi becomes ﬁ). This might be a separate issue from what you're reporting. One idea for a possible resolution would be if the vscode API returned the line display length instead of the length based on the number of characters. The problem is that in the example case of the single ligature character ﬁ, vscode reports its length as 2 instead of 1.
