### ISSUE TITLE
Open another file when I view it from sidebar

### ISSUE THREAD

**Issue by LeninZapata** [solomonkinard/public#16] opened 2024-08-05 17:49 UTC
It's strange, when I click on the sidebar it opens another file and this file doesn't show me the line with the little star of the indicator. That behavior is confusing.
![image](https://github.com/user-attachments/assets/751fdb15-0a7a-431b-b6c6-ccf6ecb6e3cb)

**Comment by solomonkinard** [comment] 2024-08-06 04:16
El archivo tiene el mismo nombre pero una ruta diferente?

**Comment by solomonkinard** [comment] 2024-08-11 07:21
> Does the file have the same name but a different path?

The bug doesn't have a picture showing the sidebar menu with the file bookmark visible. Plus, there hasn't been a response in this bug after some time. Closing without further details due to inability to verify what's happening by looking at the photo (missing sidebar), and therefore inability to reproduce. Thanks.

**Closed as not planned by solomonkinard** 2024-08-11 07:21 UTC
